### ISSUE TITLE
Good Job!,I would like to ask about small object detection

### ISSUE THREAD

**Issue by XcodeHw** [hoya012/deep_learning_object_detection#23]
which models are better in small object detection，Can you give me some suggestions?

**Comment by understand94** [comment]
You can try to use RetinaNet,which using the focal loss and PFN Net. If you want to get the better perfomance in small object detection, you can try to use the bigger feature map to detect, because the bigger feature map have the samll stride(receptive field) and more suitable for detect small obj.





At 2019-09-18 09:42:57, "XcodeHw" <notifications@github.com> wrote:


which models are better in small object detection，Can you give me some suggestions?

**Comment by sebgao** [comment]
You can try our LIP-ResNet(https://github.com/sebgao/LIP/) as backbones. LIP in backbones can significantly improve small object detections on the COCO dataset without any modification on detection framework.
